export enum IconsTypes {
  PLUS = 'plus',
  DELETE = 'delete',
  CLOSE = 'close',
  EDIT = 'edit',
  SEARCH = 'search',
  PENCIL = 'pencil',
  DATE_START = 'date-start',
  DATE_END = 'date-end',
  SUN = 'sun',
  MOON = 'moon',
  ALERT = 'alert',
  EMAIL = 'email',
  PASSWORD = 'password',
  SPINNER = 'spinner',
  EYE_ON = 'eye-on',
  EYE_OFF = 'eye-off',
}
