export const FIRST_ARR_INDEX = 1;
export const LINK_EXP_TIME = 1000 * 60 * 15;
export const RESET_LINK_DIVIDER = '-';
export const AUTH_HEADER_DIVIDER = ' ';
export const MODE_DEV = 'dev';
export const RESET_PREFIX = 'todo-app-trainee-camp/#/reset-password/';

export const EXPIRED_ACCESS_TOKEN =
  'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODE4NzdkODU3YWQ0MGZkMWM4MWY3MSIsImlhdCI6MTcwMzE1NjU1MywiZXhwIjoxNzAzMTU4MzUzfQ.DujN3iU1Y4hiHPQOTxDgNf166kgX42FnPgrBkqs-Jfk';

export const VALID_ACCESS_TOKEN_USER_1 =
  'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODE4NzdkODU3YWQ0MGZkMWM4MWY3MSIsImlhdCI6MTcwMzE2Njk5MiwiZXhwIjoxNzA1NzU4OTkyfQ.6QZbAdDyYBODvUy6K9HULElCirKI8v0FMbLnKwdIsmc';
export const VALID_ACCESS_TOKEN_USER_2 =
  'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ODE4NzlkODU3YWQ0MGZkMWM4MWY3MyIsImlhdCI6MTcwMzE2NzAwOCwiZXhwIjoxNzA1NzU5MDA4fQ.8np3L-MP50n_rI0iBrWOnK4tKJCKChGdC7tOkLmpr64';
